### ISSUE TITLE
Jira-link is hardcoded 

### ISSUE THREAD

**Issue by Mtze** [ls1intum/prototyper_web#1]
I tried to change the authentication-service url and it took me a while to find it in the code... Please include the Jira-url in the config files.

Location in code:
https://github.com/ls1intum/prototyper_web/blob/fe97596eebe0f1619a6c187a8da99b64cf25482f/app/helpers/users_helper.rb#L2

Thanks :)

**Comment by grafele** [comment]
Handled in https://github.com/ls1intum/prototyper_web/pull/3
